FROM node:16-alpine

# USER node

#RUN mkdir -p /home/node/app
#WORKDIR /home/node/app
WORKDIR /app

#COPY --chown=node:node ./package.json ./
COPY ./package.json ./
RUN npm install

#COPY --chown=node:node ./ ./
COPY ./ ./

CMD ["npm", "run", "start"]
